swagger: "2.0"
info: {}
basePath: /v1
paths:
  /product/:
    get:
      tags:
      - product
      summary: Lấy một sản phẩm
      description: Get Product
      operationId: ProductController.Get Product
      parameters:
      - in: query
        name: pid
        description: product id
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/responses.ResponseSingle'
        "404":
          description: '{object} responses.ResponseSingle'
    put:
      tags:
      - product
      summary: sửa một sản phẩm
      description: Up Date Product
      operationId: ProductController.Up Date Product
      parameters:
      - in: body
        name: data
        description: product
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/responses.ResponseSingle'
        "404":
          description: '{object} responses.ResponseSingle'
    post:
      tags:
      - product
      summary: Tạo mới sản phẩm
      description: Create Product
      operationId: ProductController.Create Product
      parameters:
      - in: body
        name: data
        description: product
        required: true
        schema:
          $ref: '#/definitions/requests.RequestCreateProduct'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/responses.ResponseBool'
        "404":
          description: '{object} responses.ResponseBool'
  /product/list:
    get:
      tags:
      - product
      summary: Lấy một danh sách sản phẩm
      description: Get List Product
      operationId: ProductController.Get List Product
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/responses.ResponseArray'
        "404":
          description: '{object} responses.ResponseArray'
definitions:
  98.0xc0003f95c0.false:
    title: "false"
    type: object
  165.0xc0003f9650.false:
    title: "false"
    type: object
  models.Product:
    title: Product
    type: object
    properties:
      CategoryId:
        type: integer
        format: int64
      Description:
        type: string
      Id:
        type: integer
        format: int64
      Image:
        type: string
      IsSale:
        type: boolean
      Name:
        type: string
      Price:
        type: number
        format: float
      Rate1:
        type: integer
        format: int64
      Rate2:
        type: integer
        format: int64
      Rate3:
        type: integer
        format: int64
      Rate4:
        type: integer
        format: int64
      Rate5:
        type: integer
        format: int64
      RateAvg:
        type: number
        format: float
      Remaining:
        type: integer
        format: int64
      SalePrice:
        type: number
        format: float
      Sold:
        type: integer
        format: int64
      Unit:
        type: string
  requests.RequestCreateProduct:
    title: RequestCreateProduct
    type: object
    properties:
      CategoryId:
        type: integer
        format: int64
      Description:
        type: string
      Image:
        type: string
      IsSale:
        type: boolean
      Name:
        type: string
      Price:
        type: number
        format: float
      Remaining:
        type: integer
        format: int64
      SalePrice:
        type: number
        format: float
      Sold:
        type: integer
        format: int64
      Unit:
        type: string
  responses.Err:
    title: Err
    type: object
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
  responses.ResponseArray:
    title: ResponseArray
    type: object
    properties:
      Data:
        $ref: '#/definitions/165.0xc0003f9650.false'
      Error:
        $ref: '#/definitions/responses.Err'
      TotalCount:
        type: integer
        format: int64
  responses.ResponseBool:
    title: ResponseBool
    type: object
    properties:
      Error:
        $ref: '#/definitions/responses.Err'
  responses.ResponseSingle:
    title: ResponseSingle
    type: object
    properties:
      Data:
        $ref: '#/definitions/98.0xc0003f95c0.false'
      Error:
        $ref: '#/definitions/responses.Err'
