swagger: "2.0"
info: {}
basePath: /v1
paths:
  /product/:
    get:
      tags:
      - product
      summary: Lấy một sản phẩm
      description: Get Product
      operationId: ProductController.Get Product
      parameters:
      - in: query
        name: pid
        description: product id
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/responses.ResponseSingle'
        "404":
          description: '{object} responses.ResponseSingle'
    post:
      tags:
      - product
      summary: Tạo mới sản phẩm
      description: Create Product
      operationId: ProductController.Create Product
      parameters:
      - in: body
        name: data
        description: product
        required: true
        schema:
          $ref: '#/definitions/requests.RequestCreateProduct'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/responses.ResponseBool'
        "404":
          description: '{object} responses.ResponseBool'
definitions:
  requests.RequestCreateProduct:
    title: RequestCreateProduct
    type: object
    properties:
      CategoryId:
        type: integer
        format: int64
      Description:
        type: string
      Image:
        type: string
      IsSale:
        type: boolean
      Name:
        type: string
      Price:
        type: number
        format: float
      Remaining:
        type: integer
        format: int64
      SalePrice:
        type: number
        format: float
      Sole:
        type: integer
        format: int64
      Unit:
        type: string
  responses.Err:
    title: Err
    type: object
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
  responses.ResponseBool:
    title: ResponseBool
    type: object
    properties:
      Error:
        $ref: '#/definitions/responses.Err'
  responses.ResponseSingle:
    title: ResponseSingle
    type: object
    properties:
      Data:
        additionalProperties:
          type: string
      Error:
        $ref: '#/definitions/responses.Err'
