swagger: "2.0"
info: {}
basePath: /v1
paths:
  /account/:
    get:
      tags:
      - account
      summary: check tồn tại token
      description: Check Exist Token
      operationId: AccountController.Check Exist Token
      parameters:
      - in: query
        name: token
        description: token
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/responses.ResponseSingle'
        "404":
          description: '{object} responses.ResponseSingle'
  /account/login:
    post:
      tags:
      - account
      summary: đăng nhập
      description: Login
      operationId: AccountController.Login
      parameters:
      - in: body
        name: data
        description: login
        required: true
        schema:
          $ref: '#/definitions/requests.RequestLogin'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/responses.ResponseSingle'
        "404":
          description: '{object} responses.ResponseSingle'
  /account/register:
    post:
      tags:
      - account
      summary: Tạo mới tài khoản
      description: Register
      operationId: AccountController.Register
      parameters:
      - in: body
        name: req
        description: req
        required: true
        schema:
          $ref: '#/definitions/requests.RequestRegister'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/responses.ResponseBool'
        "404":
          description: '{object} responses.ResponseBool'
  /admin/:
    post:
      tags:
      - admin
      summary: Tạo mới tài khoản
      description: Create Account
      operationId: AdminController.Create Account
      parameters:
      - in: header
        name: token
        description: Token
        required: true
        type: string
      - in: body
        name: req
        description: req
        required: true
        schema:
          $ref: '#/definitions/requests.RequestCreateAccount'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/responses.ResponseBool'
        "404":
          description: '{object} responses.ResponseBool'
  /cart/:
    get:
      tags:
      - cart
      summary: Lấy danh sách sản phẩm trong giỏ hàng
      description: Get List Item In Cart
      operationId: CartController.Get List Item In Cart
      parameters:
      - in: header
        name: token
        description: Token
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/responses.ResponseArray'
        "404":
          description: '{object} responses.ResponseArray'
    post:
      tags:
      - cart
      summary: thêm sản phẩm vào giỏ hàng
      description: Set Item InTo Cart
      operationId: CartController.Set Item Into Cart
      parameters:
      - in: header
        name: token
        description: Token
        required: true
        type: string
      - in: body
        name: data
        description: ProductId and quantity
        required: true
        schema:
          $ref: '#/definitions/requests.RequestCart'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/responses.ResponseArray'
        "404":
          description: '{object} responses.ResponseArray'
    delete:
      tags:
      - cart
      summary: xóa sản phẩm trong giỏ hàng
      description: Delete Item In Cart
      operationId: CartController.Delete Item In Cart
      parameters:
      - in: header
        name: token
        description: Token
        required: true
        type: string
      - in: query
        name: pid
        description: ProductId
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/responses.ResponseBool'
        "404":
          description: '{object} responses.ResponseBool'
  /category/:
    get:
      tags:
      - category
      summary: Lấy danh sách loại sản phẩm
      description: Get List Category
      operationId: CategoryController.Get List Category
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/responses.ResponseArray'
        "404":
          description: '{object} responses.ResponseArray'
    put:
      tags:
      - category
      summary: sửa một loại sản phẩm
      description: Update Category
      operationId: CategoryController.Update Category
      parameters:
      - in: header
        name: token
        description: Token
        required: true
        type: string
      - in: body
        name: data
        description: category
        required: true
        schema:
          $ref: '#/definitions/models.Category'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/responses.ResponseBool'
        "404":
          description: '{object} responses.ResponseBool'
    post:
      tags:
      - category
      summary: Tạo một loại sản phẩm
      description: Create Category
      operationId: CategoryController.Create Category
      parameters:
      - in: header
        name: token
        description: Token
        required: true
        type: string
      - in: body
        name: name
        description: name categorry
        required: true
        schema:
          type: string
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/responses.ResponseBool'
        "404":
          description: '{object} responses.ResponseBool'
  /comment/:
    get:
      tags:
      - comment
      summary: Lấy danh sách bình luận
      description: Get List Comment
      operationId: CommentController.Get List Comment
      parameters:
      - in: query
        name: pid
        description: product id
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/responses.ResponseArray'
        "404":
          description: '{object} responses.ResponseArray'
    post:
      tags:
      - comment
      summary: Tạo mới bình luận
      description: Create Comment
      operationId: CommentController.Create Comment
      parameters:
      - in: header
        name: token
        description: Token
        required: true
        type: string
      - in: body
        name: data
        description: comment
        required: true
        schema:
          $ref: '#/definitions/requests.RequestComment'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/responses.ResponseBool'
        "404":
          description: '{object} responses.ResponseBool'
  /order/:
    put:
      tags:
      - order
      summary: sửa đơn hàng
      description: Update Category
      operationId: OrderController.Update Category
      parameters:
      - in: header
        name: token
        description: Token
        required: true
        type: string
      - in: body
        name: id
        description: id order
        required: true
        schema:
          type: string
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/responses.ResponseBool'
        "404":
          description: '{object} responses.ResponseBool'
    post:
      tags:
      - order
      summary: thanh toán đơn hàng
      description: Pay Order
      operationId: OrderController.Pay Order
      parameters:
      - in: header
        name: token
        description: Token
        required: true
        type: string
      - in: body
        name: data
        description: order
        required: true
        schema:
          $ref: '#/definitions/requests.RequestOrder'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/responses.ResponseBool'
        "404":
          description: '{object} responses.ResponseBool'
  /order/list:
    get:
      tags:
      - order
      summary: Lấy danh sách đặt hàng
      description: Get List Order
      operationId: OrderController.Get List Order
      parameters:
      - in: header
        name: token
        description: Token
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/responses.ResponseArray'
        "404":
          description: '{object} responses.ResponseArray'
  /order/listAll:
    get:
      tags:
      - order
      summary: Lấy danh sách đặt hàng
      description: Get List Order
      operationId: OrderController.Get List Order
      parameters:
      - in: header
        name: token
        description: Token
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/responses.ResponseArray'
        "404":
          description: '{object} responses.ResponseArray'
  /product/:
    put:
      tags:
      - product
      summary: sửa một sản phẩm
      description: Update Product
      operationId: ProductController.Update Product
      parameters:
      - in: header
        name: token
        description: Token
        required: true
        type: string
      - in: body
        name: data
        description: product
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/responses.ResponseSingle'
        "404":
          description: '{object} responses.ResponseSingle'
    post:
      tags:
      - product
      summary: Tạo mới sản phẩm
      description: Create Product
      operationId: ProductController.Create Product
      parameters:
      - in: header
        name: token
        description: Token
        required: true
        type: string
      - in: body
        name: data
        description: product
        required: true
        schema:
          $ref: '#/definitions/requests.RequestCreateProduct'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/responses.ResponseBool'
        "404":
          description: '{object} responses.ResponseBool'
  /product/{pid}:
    get:
      tags:
      - product
      summary: Lấy một sản phẩm
      description: Get Product
      operationId: ProductController.Get Product
      parameters:
      - in: path
        name: pid
        description: product id
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/responses.ResponseSingle'
        "404":
          description: '{object} responses.ResponseSingle'
  /product/list:
    get:
      tags:
      - product
      summary: Lấy một danh sách sản phẩm
      description: Get List Product
      operationId: ProductController.Get List Product
      parameters:
      - in: query
        name: page
        description: page
        type: integer
        format: int64
      - in: query
        name: size
        description: size
        type: integer
        format: int64
      - in: query
        name: cateid
        description: cate id
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/responses.ResponseArray'
        "404":
          description: '{object} responses.ResponseArray'
  /user/:
    put:
      tags:
      - user
      summary: sửa thông tin người dùng
      description: Update User
      operationId: UserController.Update User
      parameters:
      - in: header
        name: token
        description: Token
        required: true
        type: string
      - in: body
        name: data
        description: data
        required: true
        schema:
          $ref: '#/definitions/requests.RequestUser'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/responses.ResponseBool'
        "404":
          description: '{object} responses.ResponseBool'
definitions:
  871.0xc0005fb020.false:
    title: "false"
    type: object
  997.0xc0005fb0b0.false:
    title: "false"
    type: object
  models.Category:
    title: Category
    type: object
    properties:
      category_id:
        type: integer
        format: int64
      name:
        type: string
  models.Product:
    title: Product
    type: object
    properties:
      category_id:
        type: integer
        format: int64
      description:
        type: string
      id:
        type: integer
        format: int64
      image:
        type: string
      is_sale:
        type: boolean
      name:
        type: string
      price:
        type: number
        format: float
      rate_avg:
        type: number
        format: float
      rate1:
        type: integer
        format: int64
      rate2:
        type: integer
        format: int64
      rate3:
        type: integer
        format: int64
      rate4:
        type: integer
        format: int64
      rate5:
        type: integer
        format: int64
      remaining:
        type: integer
        format: int64
      sale_price:
        type: number
        format: float
      sold:
        type: integer
        format: int64
      unit:
        type: string
  requests.RequestCart:
    title: RequestCart
    type: object
    properties:
      product_id:
        type: integer
        format: int64
      quantity:
        type: integer
        format: int64
  requests.RequestComment:
    title: RequestComment
    type: object
    properties:
      comment:
        type: string
      product_id:
        type: integer
        format: int64
  requests.RequestCreateAccount:
    title: RequestCreateAccount
    type: object
    properties:
      email:
        type: string
      gender:
        type: string
      image:
        type: string
      name:
        type: string
      pass:
        type: string
      phone:
        type: string
      type:
        type: string
      username:
        type: string
  requests.RequestCreateProduct:
    title: RequestCreateProduct
    type: object
    properties:
      category_id:
        type: integer
        format: int64
      description:
        type: string
      image:
        type: string
      is_sale:
        type: boolean
      name:
        type: string
      price:
        type: number
        format: float
      remaining:
        type: integer
        format: int64
      sale_price:
        type: number
        format: float
      sold:
        type: integer
        format: int64
      unit:
        type: string
  requests.RequestLogin:
    title: RequestLogin
    type: object
    properties:
      pass:
        type: string
      username:
        type: string
  requests.RequestOrder:
    title: RequestOrder
    type: object
    properties:
      address:
        type: string
      detail:
        type: array
        items:
          $ref: '#/definitions/requests.RequestOrderDetail'
      lastUpdate:
        type: integer
        format: int64
      name:
        type: string
      number:
        type: string
  requests.RequestOrderDetail:
    title: RequestOrderDetail
    type: object
    properties:
      product_id:
        type: integer
        format: int64
      quantity:
        type: integer
        format: int64
  requests.RequestRegister:
    title: RequestRegister
    type: object
    properties:
      email:
        type: string
      gender:
        type: string
      image:
        type: string
      name:
        type: string
      pass:
        type: string
      phone:
        type: string
      username:
        type: string
  requests.RequestUser:
    title: RequestUser
    type: object
    properties:
      email:
        type: string
      gender:
        type: string
      image:
        type: string
      name:
        type: string
      phone:
        type: string
  responses.Err:
    title: Err
    type: object
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
  responses.ResponseArray:
    title: ResponseArray
    type: object
    properties:
      data:
        $ref: '#/definitions/997.0xc0005fb0b0.false'
      error:
        $ref: '#/definitions/responses.Err'
      total_count:
        type: integer
        format: int64
  responses.ResponseBool:
    title: ResponseBool
    type: object
    properties:
      error:
        $ref: '#/definitions/responses.Err'
  responses.ResponseSingle:
    title: ResponseSingle
    type: object
    properties:
      data:
        $ref: '#/definitions/871.0xc0005fb020.false'
      error:
        $ref: '#/definitions/responses.Err'
