package routers

import (
	"github.com/astaxie/beego"
	"new-order-food/controllers"
)

func init() {
	ns := beego.NewNamespace("/v1",
		beego.NSNamespace("/product",
			beego.NSInclude(
				&controllers.ProductController{},
			),
		),
		beego.NSNamespace("/category",
			beego.NSInclude(
				&controllers.CategoryController{},
			),
		),
		beego.NSNamespace("/account",
			beego.NSInclude(
				&controllers.AccountController{},
			),
		),
		beego.NSNamespace("/cart",
			beego.NSInclude(
				&controllers.CartController{},
			),
		),
		beego.NSNamespace("/order",
			beego.NSInclude(
				&controllers.OrderController{},
			),
		),
		beego.NSNamespace("/user",
			beego.NSInclude(
				&controllers.UserController{},
			),
		),
		beego.NSNamespace("/admin",
			beego.NSInclude(
				&controllers.AdminController{},
			),
		),
		beego.NSNamespace("/comment",
			beego.NSInclude(
				&controllers.CommentController{},
			),
		),
		beego.NSNamespace("/rate",
			beego.NSInclude(
				&controllers.RateController{},
			),
		),
		beego.NSNamespace("/discount",
			beego.NSInclude(
				&controllers.DiscountController{},
			),
		),
		beego.NSNamespace("/vendor",
			beego.NSInclude(
				&controllers.VendorController{},
			),
		),
		beego.NSNamespace("/import",
			beego.NSInclude(
				&controllers.ImportController{},
			),
		),
	)
	beego.AddNamespace(ns)
}
